### ISSUE TITLE
GUI not working after typing qtgui on command line inside putty

### ISSUE THREAD

**Issue by CoderBoogs** [openoms/bitcoin-tutorials#34]
I followed all the steps and inside putty  after I type qtgui
I get this: 

# opening the JoinMarket-QT GUI with the command: '(jmvenv) python joinmarket-qt.py'

xming is running in the background but the GUI window never comes up.

**Comment by openoms** [comment]
you are probably referring to the instructions in joininbox: https://github.com/openoms/joininbox/blob/master/scripts/info.qtgui.sh#L69

Are you running on a RaspiBlitz or else?

In this repo the process is described in bit more detail:
https://github.com/openoms/bitcoin-tutorials/tree/master/joinmarket#windows

make sure to:  
* connect with ssh -X
* the QT GUI dependencies are installed

**Comment by CoderBoogs** [comment]
got it. found my issue. thanks @openoms

**Comment by openoms** [comment]
ok, I found an issue too: the `qtgui` shortcut is not complete so will be an easy fix.

for now instead of `qtgui` use the command:
`python ~/joinmarket-clientserver/scripts/joinmarket-qt.py`
or the long version:
`~/joinmarket-clientserver/jmvenv/bin/python ~/joinmarket-clientserver/scripts/joinmarket-qt.py`

**Comment by CoderBoogs** [comment]
okay thanks.
